config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/feed", to: "feeds#index"
    get "/search", to: "search#index"
    get "/topuser", to: "users#index"
    get "/bookmarks", to: "bookmarks#index"

    resources :categories
    resources :users
    resources :recipes do
      resources :comments, only: [:create, :destroy]
    end

    resources :users do
      resources :recipes do
        resources :favors, only: [:create, :destroy]
        resources :bookmarks, only: [:create, :destroy]
      end
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.order_by_name
    @recipes = Recipe.hot_recipe.desc
    @topusers = User.top_user
  end
end

app/views/static_pages/_category.html.erb
<ul class="thumbnails">
  <% @categories.take(Settings.num_category).each do |cate| %>
    <li class="col-xs-2">
      <%= link_to cate.name, category_path(cate.id), class: "btn btn-lg
        btn-danger category" %></li>
  <% end %>
  <li calss="col-xs-2">
    <button class="btnsh btn btn-lg btn-danger category">...</button>
  </li>
</ul>
<ul class="thumbnails showhide">
  <% @categories.drop(Settings.num_category).each do |cate| %>
    <li class="col-xs-2">
      <%= link_to cate.name, category_path(cate.id), class: "btn btn-lg
        btn-danger category" %></li>
  <% end %>
</ul>

app/views/static_pages/_recipe.html.erb
<% @recipes.each do |recipe| %>
  <div class="col-md-4">
    <div class="recipe">
    <%= link_to image_tag(recipe.cover_photo.url.to_s,
      class: "img-responsive img-rounded center-block", size: "250x150"), recipe_path(recipe) %>
      <div class="bottom-left">
        <ul class="list-inline">
          <li><i class="fa fa-bolt"></i><%= recipe.difficult_level %></li>
          <li><i class="fa fa-clock-o"></i><%= recipe.ready_in %></li>
          <li><i class="fa fa-eye"></i><%= recipe.impressionist_count %>
            </li>
        </ul>
      </div>
    </div>
    <div class="text-center">
      <%= link_to recipe.name, recipe_path(recipe), class: "small" %>
      <p>
        <%= t "static_pages.home.recipe_by" %>
        <%= link_to recipe.user.name, user_path(recipe.user), class: "small" %>
      </p>
    </div>
  </div>
<% end %>

app/views/static_pages/_topuser.html.erb
<div class = "well">
  <% @topusers.first(10).each do |user| %>
    <div class="row">
      <div class="col-md-3">
        <%= link_to image_tag(user.avatar.to_s,class: "img-responsive img-circle",
        size: "50x50"), user_path(user) %>
      </div>
      <div class="col-md-9">
        <p>
          <b><%= link_to user.name, user_path(user) %></b>
        </p>
        <p><%= user.recipes.count %><%= t "static_pages.home.recipe" %> | <span><%= user.followers.count %><%= t "static_pages.home.followers" %>
        </span></p>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="pull-right">
      <b><%= link_to t("static_pages.home.link_topuser"), topuser_path %></b>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid">
  <!-- START JUMBOTRON -->
  <div class="jumbotron" id="main-jumbotron">
    <div class = "row">
      <div class = "col-md-7">
        <h1><%= t ".today" %></h1>
        <div class="search-form">
        <%= form_for :reci, url: search_path, html: {class: "navbar-form"}, method: :get do |form| %>
          <%= text_field_tag :reci, params[:reci], class: "form-control" %>
          <%= submit_tag("Search", name: nil, class: "btn btn-primary") do %>
            <i class="fa fa-search"></i>
          <% end %>
        <% end %>
        </div>
        <p><%= t ".description" %></p>
      </div>
      <div class = "col-md-5">
        <%= render "carousel" %>
      </div>
    </div>

  </div>
  <!-- END JUMBOTRON -->
  <!-- START CATEGORIES -->
  <div class="row">
    <%= render "category" %>
  </div>
  <!-- END CATEGORIES -->
  <hr>
  <div class="row">
    <!-- START RECIPES -->
    <div class="col-md-9">
      <h1><%= t ".trending" %></h1>
      <div class="row">
          <%= render @recipes, divide: "4" %>
      </div>
    </div>
    <!-- END RECIPES -->
    <!-- START TOP MEMBER -->
    <div class="col-md-3">
      <h1><%= t ".top_member" %></h1>
      <%= render "topuser" %>
    </div>
    <!-- END TOP MEMBER -->
  </div>
</div>