config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/feed", to: "feeds#index"
    get "/search", to: "search#index"
    get "/topuser", to: "users#index"
    get "/bookmarks", to: "bookmarks#index"

    resources :categories
    resources :users
    resources :recipes do
      resources :comments, only: [:create, :destroy]
    end

    resources :users do
      resources :recipes do
        resources :favors, only: [:create, :destroy]
        resources :bookmarks, only: [:create, :destroy]
      end
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: User.name
  belongs_to :recipe, class_name: Recipe.name

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: :destroy
  before_action :find_recipe, only: %i(create destroy)

  def new; end

  def create
    @comment = Comment.new comment_params

    if @comment.save
      respond_to do |format|
        format.html{redirect_to @recipe}
        format.js{render layout: false}
      end
    else
      render js: "alert(I18n.t('empty_comment_alert'))"
    end
  end

  def destroy
    @comment = @recipe.comments.find_by id: params[:id]
    @comment.destroy
    respond_to do |format|
      format.html{redirect_to recipe_path @recipe}
      format.js
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find_by id: params[:recipe_id]
  end

  def comment_params
    params.require(:comment).permit(:content,
      :recipe_id).merge user_id: current_user.id
  end

  def correct_user
    @comment = current_user.comments.find_by id: params[:id]
    redirect_to root_url unless @comment
  end
end

app/views/comments/_comment.html.erb
<div class="row cmt" id = "comment-<%= comment.id %>">
  <div class="col-md-2">
    <%= image_tag comment.user.avatar.url.to_s, class: "img-responsive pull-right img-circle", size: "50x50" %>
  </div>
  <div class="col-md-8">
    <strong><%= comment.user.name %></strong>
    <br>
    <p><%= comment.content %></p>
  </div>
  <div class="col-md-2">
    <% if comment.user.current_user? current_user %>
      <p><%= link_to t(".delete"), recipe_comment_path(@recipe, comment), method: :delete, remote: :true, data: {confirm: t(".confirm")}, class: "delete-comment" %></p>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for @comment, url: recipe_comments_path(@recipe), class: "add-comment-btn", remote: :true do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <div class="field">
    <%= form.label :content, t(".add_comment") %>
    <%= form.text_area :content, class: "form-control field-input comment-input" %>
    <%= form.hidden_field :recipe_id %>
  </div>

  <div class="actions">
    <%= form.submit t(".submit"), class: "btn btn-danger" %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('.comment').append("<%= escape_javascript(render @comment) %>");
$('.comment-input').val("");

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").fadeOut();