config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/feed", to: "feeds#index"
    get "/search", to: "search#index"
    get "/topuser", to: "users#index"
    get "/bookmarks", to: "bookmarks#index"

    resources :categories
    resources :users
    resources :recipes do
      resources :comments, only: [:create, :destroy]
    end

    resources :users do
      resources :recipes do
        resources :favors, only: [:create, :destroy]
        resources :bookmarks, only: [:create, :destroy]
      end
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]
  end
end

app/models/favor.rb
class Favor < ApplicationRecord
  belongs_to :user
  belongs_to :targetable, polymorphic: true

  enum status: {like_comment: 0, like_recipe: 1, bookmark_recipe: 2}

  scope :rela, ->(user_id, targetable){where user_id: user_id, targetable: targetable, status: 1}
  scope :rela_bookmark, ->(user_id, targetable){where user_id: user_id, targetable: targetable, status: 2}
  scope :bookmark_list, ->(user_id){where(user_id: user_id, status: 2).pluck(:targetable_id)}
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  before_action :find_recipe, only: %i(create destroy)

  def create
    return if current_user.liked? @recipe
    if params[:status] == "1"
      @favor = Favor.new status: "like_recipe", user: current_user,
        targetable: @recipe
      if @favor.save
        @favor = Favor.rela current_user.id, @recipe
        respond_to do |format|
          format.html {redirect_to @recipe}
          format.js
        end
      else
        flash[:warning] = t ".failed"
      end
    end
  end

  def destroy
    @favor = Favor.find_by id: params[:id]
    @favor.destroy
    respond_to do |format|
      format.html {redirect_to @recipe}
      format.js
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find_by id: params[:recipe_id]

    return if @recipe
    redirect_to root_path
  end
end

app/views/favors/_like.html.erb
  <%= link_to user_recipe_favors_path(current_user, recipe, status: 1), method: :post, remote: true do %>
    <button class="btn btn-default">
      <i class="fa fa-thumbs-o-up"></i>
      <span><%= t ".like_recipe" %></span>
    </button>
  <% end %>

app/views/favors/_like_form.html.erb
<% if current_user.liked? recipe %>
  <div id="ajax-like-unlike"><%= render "favors/unlike", recipe: recipe, favor: favor %></div>
<% else %>
  <div id="ajax-like-unlike"><%= render "favors/like", recipe: recipe %></div>
<% end %>

app/views/favors/_unlike.html.erb
<%= link_to user_recipe_favor_path(current_user, recipe, favor.ids), method: :delete, remote: true do %>
  <button class="btn btn-primary">
    <i class="fa fa-thumbs-up like-text"></i>
    <span class="like-text"><%= t ".unlike_recipe" %></span>
  </button>
<% end %>

app/views/favors/create.js.erb
$("#ajax-like-unlike").html("<%= j render('unlike', recipe: @recipe, favor: @favor) %>");

app/views/favors/destroy.js.erb
$("#ajax-like-unlike").html("<%= j render('like', recipe: @recipe, favor: @favor) %>");