config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/feed", to: "feeds#index"
    get "/search", to: "search#index"
    get "/topuser", to: "users#index"
    get "/bookmarks", to: "bookmarks#index"

    resources :categories
    resources :users
    resources :recipes do
      resources :comments, only: [:create, :destroy]
    end

    resources :users do
      resources :recipes do
        resources :favors, only: [:create, :destroy]
        resources :bookmarks, only: [:create, :destroy]
      end
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favors, as: :targetable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorite_recipes, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id",
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :comments, dependent: :destroy

  scope :top_user, ->{joins(:recipes).group(:id).order("count(recipes.id)
   DESC").limit(Settings.num_top_user)}

  mount_uploader :avatar, AvatarUploader

  before_save :email_downcase

  validates :name, presence: true,
            length: {maximum: Settings.name_max_length}
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            length: {maximum: Settings.email_max_length},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, presence: true,
            length: {minimum: Settings.password_min_length}, allow_nil: true
  validate :avatar_size
  has_secure_password

  def current_user? user
    self == user
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  def feed
    @recipes = Recipe.feed(following_ids, id).desc
  end

  def liked? recipe
    @rela = Favor.rela self, recipe
    @rela.present?
  end

  def bookmarked? recipe
    @rela = Favor.rela_bookmark self, recipe
    @rela.present?
  end

  private

  def email_downcase
    email.downcase!
  end

  def avatar_size
    return unless avatar.size > Settings.max_file.megabytes
    errors.add :avatar, I18n.t(".over_limit_file_size")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :find_user, except: [:new, :create, :index]
  before_action :correct_user, except: [:show, :index]

  def show
    @recipes = @user.recipes.desc.page(params[:page])
                    .per Settings.user_per_show
  end

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t ".welcome"
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".save_success"
      redirect_to @user
    else
      flash[:danger] = t ".save_failed"
      render :edit
    end
  end

  def index
    @users = User.top_user
  end

  private

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t ".cant_find"
    redirect_to root_path
  end

  def correct_user
    redirect_to root_path unless current_user? @user
  end

  def user_params
    params.require(:user).permit :name, :address, :email, :avatar,
     :password, :password_confirmation
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit t("users.show.follow"), class: "btn btn-primary center-block
    " %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form-<%= user.id %>">
  <% if current_user.following?(user) %>
    <%= render "users/unfollow", user: user %>
  <% else %>
    <%= render "users/follow", user: user %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name do %>
    <span><%= t ".name" %> *</span>
  <% end %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :address, t(".address") %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :email do %>
    <span><%= t ".email" %> *</span>
  <% end %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password do %>
    <span><%= t ".password" %> *</span>
  <% end %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation do %>
    <span><%= t ".password_confirmation" %> *</span>
  <% end %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :avatar, t(".avatar") %>
  <%= f.file_field :avatar,
    accept: "image/jpeg,image/gif,image/png,image/jpg" %>
  <br>
  <%= f.submit yield(:btn_text), class: "btn btn-primary" %>
  <%= link_to t(".back"), @user, class: "btn btn-default" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit t("users.show.unfollow"), class: "btn btn-default center-block" %>
<% end %>

app/views/users/edit.html.erb
<% provide :btn_text, (t ".edit_btn") %>
<h1 class="text-center"><%= t ".title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
<h1><%= t ".top20" %></h1>
  <% @users.each do |user| %>
    <div class="col-md-2">
      <div class="well text-center">
        <% if user.avatar.url %>
          <%= link_to image_tag(user.avatar.to_s, class: "img-circle
            center-block", size: "150x150"), user_path(user) %>
        <% else %>
          <%= link_to image_tag("default_avatar.png", class: "img-responsive
            img-circle center-block ", size: "#{Settings.img_size_fill}x#{Settings.img_size_fill}"), user_path(user) %>
        <% end %>
        <h5><%= link_to user.name, user_path(user) %></h5>
        <p><i class="fa fa-users fa-2x"></i><%= user.followers.count %><%= t ".follower" %></p>
        <% if logged_in? %>
          <%= render "follow_form", user: user %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide :btn_text, (t ".create_btn") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class = "well">
      <h1 class="text-center"><%= t ".signup" %></h1>
        <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 well">
      <% if @user.avatar.url %>
        <%= image_tag(@user.avatar.to_s,
          class: "img-circle center-block avatar-show") %>
      <% else %>
        <%= image_tag("default_avatar.png",
          class: "img-responsive img-circle center-block",
          size: "#{Settings.img_size_fill}x#{Settings.img_size_fill}") %>
      <% end %>
      <h3 class="text-center"><%= @user.name %></h3>
        <ul class="list-inline text-center">
          <li><i class="fa fa-users fa-2x"></i><br><%= @user.followers.count %>
            <%=t ".follower" %>
          </li>
          <li><i class="fa fa-thumbs-up fa-2x"></i><br><%= t ".like" %></li>
        </ul>
      <p><i class="fa fa-envelope"></i>
        <b><%= t ".email" %>:</b> <%= @user.email %>
      </p>
      <% if @user.address.present? %>
        <p><i class="fa fa-address-card"></i>
          <b><%= t ".address" %>: </b> <%= @user.address %>
        </p>
      <% end %>
      <p><i class="fa fa-calendar-check-o"></i>
        <%= t ".joined_at" %> <%= @user.created_at.strftime("%d/%m/%Y") %>
      </p>


      <% if current_user? @user %>
        <%= link_to edit_user_path, class: "btn btn-primary center-block" do %>
          <i class="fa fa-pencil-square-o"></i> <%= t ".manage_account" %>
        <% end %>
      <% else %>
        <% if logged_in? %>
          <%= render "follow_form", user: @user %>
        <% end %>
      <% end %>

    </div>
    <div class="col-md-9">
      <div class="row">
        <h2><b><%= @user.recipes.count %></b> <%= t ".recipe" %></h2>
        <% @recipes.each do |recipe| %>
        <div class="col-md-6">
          <div class="well" style="width: 440px">
            <div class="row">
                <div class="col-md-4">
                  <%= image_tag recipe.cover_photo.url.to_s, size: "125x125",
                    class: "img-rounded" %>
                </div>
                <div class="col-md-8">
                  <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
                  <p>
                    <%= truncate recipe.description,
                    length: Settings.truncate_description %>
                  </p>
                  <div class="reaction-field pull-right">
                    <button class="btn btn-sm">
                      <i class="fa fa-heart-o"></i> 6
                    </button>
                    <% if current_user? @user %>
                      <%= link_to edit_recipe_path(recipe),
                        class: "btn btn-sm btn-danger" do %>
                        <i class="fa fa-pencil-square-o"></i>
                      <% end %>
                      <%= link_to recipe_path(recipe), method: :delete, data: {confirm: t("sure")},
                        class: "btn btn-sm btn-warning" do %>
                        <i class="fa fa-trash-o"></i>
                      <% end %>
                    <% end %>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <%= paginate @recipes, theme: "twitter-bootstrap-3" %>
    </div>
  </>
</div>